a = input()
print(a.split())
print(a.split('-'))
print(map(int, a.split()))
print(list(map(int, a.split())))
b, c = map(int, a.split())
d = list(map(int, a.split()))
e = map(int, a.split())
print(b)
print(c)
print(d)
print(e)
